name: Deploy Frontend

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main  # main 브랜치에서만 발동
    paths:
      - 'frontend/**'  # frontend 폴더의 모든 변경 감지

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 필요한 Node.js 버전으로 변경

      - name: Install dependencies and build
        run: |
          cd frontend  # frontend 폴더로 이동
          npm install  # 의존성 설치
          npm run build  # 빌드 실행

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionRole
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync build to S3
        run: |
          aws s3 sync ./frontend/build s3://${{ secrets.S3_BUCKET }} --delete  # 빌드된 파일을 S3에 업로드

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"  # CloudFront 캐시 무효화